# -*- coding: utf-8 -*-
"""photocollage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-cbbUipl5uve5AvaiIJgmbSuBEjEiNyO
"""

import os
import matplotlib.pyplot as plt
import numpy as np
import cv2
import sys
folder=sys.argv[1]
images=os.listdir(str(folder))

i=0
l=len(images)
img_array=[]
for img in images:
  path=os.path.join(folder,img)
  image=cv2.imread(path)
  image=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
  image=cv2.resize(image,(200,200))
  img_array.append(image)
  plt.imshow(image)
  plt.show()

vline=np.zeros((2,200,3),dtype='int')
vline[:,:,0]=200
plt.imshow(vline)
plt.show()
hline=np.zeros((204,2,3),dtype='int');
hline[:,:,0]=200
plt.imshow(hline)
plt.show()

imgarray=[]
for img in img_array:
  img=np.vstack((vline,img,vline))
  print(img.shape)
  img=np.hstack((hline,img,hline))
  imgarray.append(img)
  plt.imshow(img)
  plt.show()
imgarray=np.array(imgarray)

total=len(img_array)
rows=int(input("Enter no of rows"))
cols=int(input("Enter no of columns"))
k=0

imag=imgarray[0]
while True:
  if rows*cols==total:
    for i in range(rows):
      ima=hline
      for j in range(cols):
        ima=np.hstack((ima,imgarray[k]))
        k=k+1
      if(i==0):
        final=ima
      else:
        final=np.vstack((final,ima))
      del(ima)
    
    final=final.astype('float32')
    final=final/255
    image_path=input("Enter the name of file  with extension like final.png")
    plt.imsave(str(image_path),final)
    print("Image saved successfully")
    break
  else:
    print("Incorrect! enter details again")
    rows=int(input("Enter no of rows"))
    cols=int(input("Enter no of columns"))

